<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.d6fFDYe' shared service.

return $this->privates['.service_locator.d6fFDYe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'user' => array('privates', '.errored..service_locator.d6fFDYe.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.d6fFDYe": it references class "App\\Entity\\User" but no such service exists.'),
    'userManager' => array('privates', 'App\\Manager\\UserManager', 'getUserManagerService.php', true),
    'validator' => array('services', 'validator', 'getValidatorService', false),
));
