<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\AdminController' shared autowired service.

$this->services['App\Controller\AdminController'] = $instance = new \App\Controller\AdminController(($this->privates['App\Repository\UserRepository'] ?? $this->load('getUserRepositoryService.php')), ($this->privates['App\Repository\BookingRepository'] ?? $this->load('getBookingRepositoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));

$instance->setContainer(($this->privates['.service_locator.9MhUVNh'] ?? $this->load('get_ServiceLocator_9MhUVNhService.php'))->withContext('App\\Controller\\AdminController', $this));

return $instance;
