<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Manager\BookingManager' shared autowired service.

return $this->privates['App\Manager\BookingManager'] = new \App\Manager\BookingManager(($this->privates['App\Repository\BookingRepository'] ?? $this->load('getBookingRepositoryService.php')));
