<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'App\\Controller\\AdminController::deleteApiUser' => array('privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true),
    'App\\Controller\\AdminController::getApiUserProfile' => array('privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true),
    'App\\Controller\\AdminController::patchApiAdminProfile' => array('privates', '.service_locator.r4Gfxdh', 'get_ServiceLocator_R4GfxdhService.php', true),
    'App\\Controller\\AdminController::patchApiAdminUserProfile' => array('privates', '.service_locator.d6fFDYe', 'get_ServiceLocator_D6fFDYeService.php', true),
    'App\\Controller\\AdminController::postApiAdmiAddUser' => array('privates', '.service_locator.i5AcMlV', 'get_ServiceLocator_I5AcMlVService.php', true),
    'App\\Controller\\AdminController::setViewHandler' => array('privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true),
    'App\\Controller\\AnonymousController::getApiUserProfile' => array('privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true),
    'App\\Controller\\AnonymousController::postApiNewUser' => array('privates', '.service_locator.i5AcMlV', 'get_ServiceLocator_I5AcMlVService.php', true),
    'App\\Controller\\AnonymousController::setViewHandler' => array('privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true),
    'App\\Controller\\BookingController::deleteApiBooking' => array('privates', '.service_locator.l8ZYTzR', 'get_ServiceLocator_L8ZYTzRService.php', true),
    'App\\Controller\\BookingController::patchApiAdminBooking' => array('privates', '.service_locator.X9seevx', 'get_ServiceLocator_X9seevxService.php', true),
    'App\\Controller\\BookingController::postApiAdminBooking' => array('privates', '.service_locator.7YfMK4z', 'get_ServiceLocator_7YfMK4zService.php', true),
    'App\\Controller\\BookingController::setViewHandler' => array('privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true),
    'App\\Controller\\UsersController::patchApiUserProfile' => array('privates', '.service_locator.r4Gfxdh', 'get_ServiceLocator_R4GfxdhService.php', true),
    'App\\Controller\\UsersController::setViewHandler' => array('privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true),
    'App\\Controller\\AdminController:deleteApiUser' => array('privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true),
    'App\\Controller\\AdminController:getApiUserProfile' => array('privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true),
    'App\\Controller\\AdminController:patchApiAdminProfile' => array('privates', '.service_locator.r4Gfxdh', 'get_ServiceLocator_R4GfxdhService.php', true),
    'App\\Controller\\AdminController:patchApiAdminUserProfile' => array('privates', '.service_locator.d6fFDYe', 'get_ServiceLocator_D6fFDYeService.php', true),
    'App\\Controller\\AdminController:postApiAdmiAddUser' => array('privates', '.service_locator.i5AcMlV', 'get_ServiceLocator_I5AcMlVService.php', true),
    'App\\Controller\\AdminController:setViewHandler' => array('privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true),
    'App\\Controller\\AnonymousController:getApiUserProfile' => array('privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true),
    'App\\Controller\\AnonymousController:postApiNewUser' => array('privates', '.service_locator.i5AcMlV', 'get_ServiceLocator_I5AcMlVService.php', true),
    'App\\Controller\\AnonymousController:setViewHandler' => array('privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true),
    'App\\Controller\\BookingController:deleteApiBooking' => array('privates', '.service_locator.l8ZYTzR', 'get_ServiceLocator_L8ZYTzRService.php', true),
    'App\\Controller\\BookingController:patchApiAdminBooking' => array('privates', '.service_locator.X9seevx', 'get_ServiceLocator_X9seevxService.php', true),
    'App\\Controller\\BookingController:postApiAdminBooking' => array('privates', '.service_locator.7YfMK4z', 'get_ServiceLocator_7YfMK4zService.php', true),
    'App\\Controller\\BookingController:setViewHandler' => array('privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true),
    'App\\Controller\\UsersController:patchApiUserProfile' => array('privates', '.service_locator.r4Gfxdh', 'get_ServiceLocator_R4GfxdhService.php', true),
    'App\\Controller\\UsersController:setViewHandler' => array('privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true),
))), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
