<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_api_doc.model_describers.object' shared service.

return $this->privates['nelmio_api_doc.model_describers.object'] = new \Nelmio\ApiDocBundle\ModelDescriber\ObjectModelDescriber(($this->privates['property_info'] ?? $this->getPropertyInfoService()), ($this->privates['annotations.cached_reader'] ?? $this->getAnnotations_CachedReaderService()));
