<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'nelmio_api_doc.controller.swagger' shared service.

return $this->services['nelmio_api_doc.controller.swagger'] = new \Nelmio\ApiDocBundle\Controller\DocumentationController(($this->privates['nelmio_api_doc.generator_locator'] ?? $this->load('getNelmioApiDoc_GeneratorLocatorService.php')));
