version: "3.3"

services:
  api:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes:
      - ./api/:/var/www/html/

  php:
    build:
      context: php-fpm
    depends_on:
      - database
    working_dir: /code
    volumes:
      - ./api:/code
  composer:
    image: 'composer:latest'
    volumes:
      - './api:/var/www/html/'
  database:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=emotion
      - MYSQL_USER=spaceCowboy
      - MYSQL_PASSWORD=azerty
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database

  front:
    image: httpd:2.4
    ports:
      - "80:80"
    volumes:
      - ./front/:/var/www/html/
  node:
    build:
      context: node
    ports:
      - 4200:4200
    volumes:
        - ./front/:/home/node/app/frontend
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        cd /home/node/app/frontend && npm start
    expose:
      - "4200"