version: "3.3"

services:
  web:
    image: webdevops/php-nginx:7.3
    working_dir: /app
    ports:
      - 80:80
    depends_on:
      - database
    volumes:
      - .:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: "Europe/Paris"
      PHP_DISPLAY_ERRORS: 1

  database:
    image: mysql:5.6
    volumes:
      - ./docker/mysqlconf:/tmp/conf.d
      - ./docker/mysql:/tmp/mysql
    environment:
      MYSQL_DATABASE: symfonyapi
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ipssi
      MYSQL_PASSWORD: ipssi

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:  
      PMA_HOST: database
