<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.l8ZYTzR' shared service.

return $this->privates['.service_locator.l8ZYTzR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'booking' => array('privates', '.errored..service_locator.l8ZYTzR.App\\Entity\\Booking', NULL, 'Cannot autowire service ".service_locator.l8ZYTzR": it references class "App\\Entity\\Booking" but no such service exists.'),
));
