<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.X9seevx' shared service.

return $this->privates['.service_locator.X9seevx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'bookingManager' => array('privates', 'App\\Manager\\BookingManager', 'getBookingManagerService.php', true),
    'validator' => array('services', 'validator', 'getValidatorService', false),
));
