<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7YfMK4z' shared service.

return $this->privates['.service_locator.7YfMK4z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'booking' => array('privates', '.errored..service_locator.7YfMK4z.App\\Entity\\Booking', NULL, 'Cannot autowire service ".service_locator.7YfMK4z": it references class "App\\Entity\\Booking" but no such service exists.'),
    'bookingManager' => array('privates', 'App\\Manager\\BookingManager', 'getBookingManagerService.php', true),
    'validationErrors' => array('privates', '.errored..service_locator.7YfMK4z.Symfony\\Component\\Validator\\ConstraintViolationListInterface', NULL, 'Cannot autowire service ".service_locator.7YfMK4z": it references interface "Symfony\\Component\\Validator\\ConstraintViolationListInterface" but no such service exists. Did you create a class that implements this interface?'),
));
