<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.i5AcMlV' shared service.

return $this->privates['.service_locator.i5AcMlV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'user' => array('privates', '.errored..service_locator.i5AcMlV.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.i5AcMlV": it references class "App\\Entity\\User" but no such service exists.'),
    'userManager' => array('privates', 'App\\Manager\\UserManager', 'getUserManagerService.php', true),
    'validationErrors' => array('privates', '.errored..service_locator.i5AcMlV.Symfony\\Component\\Validator\\ConstraintViolationListInterface', NULL, 'Cannot autowire service ".service_locator.i5AcMlV": it references interface "Symfony\\Component\\Validator\\ConstraintViolationListInterface" but no such service exists. Did you create a class that implements this interface?'),
));
