<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_api_doc.describers.config' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/Describer/DescriberInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/Describer/ExternalDocDescriber.php';

return $this->privates['nelmio_api_doc.describers.config'] = new \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber(array('info' => array('title' => 'Bookink car', 'description' => 'API for Bookink car.', 'version' => '1.0.0'), 'securityDefinitions' => array('api_key' => array('type' => 'apiKey', 'description' => 'Enter you Api Key', 'name' => 'X-AUTH-TOKEN', 'in' => 'header'))));
