<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPSPtkuj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPSPtkuj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPSPtkuj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPSPtkuj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPSPtkuj\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'PSPtkuj',
    'container.build_id' => '5d3f8cec',
    'container.build_time' => 1561562819,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPSPtkuj');
